from sqlalchemy import BigInteger, String, ForeignKey, Integer
from sqlalchemy.orm import Mapped, mapped_column, relationship

from models.base import BaseModel
from config.constants import DEFAULT_CURRENCY


class Payment(BaseModel):
    """
    Represents a payment transaction.
    """
    __tablename__ = "payments"

    # Foreign key linking this payment to a user.
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # The amount in NGN (in the smallest currency unit, e.g., kobo).
    # Paystack works with kobo, so 1000 NGN = 100000 kobo.
    amount_ngn: Mapped[int] = mapped_column(
        Integer,  # Use Integer for kobo, BigInteger if amounts can exceed ~2.1 billion kobo
        nullable=False,
        comment="Amount in the smallest currency unit (e.g., kobo for NGN)"
    )

    # The currency of the transaction. Hardcoded to 'NGN' as per the blueprint.
    currency: Mapped[str] = mapped_column(
        String(3),
        default=DEFAULT_CURRENCY,
        nullable=False
    )

    # The status of the payment. E.g., 'pending', 'successful', 'failed'.
    status: Mapped[str] = mapped_column(
        String(50),
        default="pending",
        nullable=False,
        index=True
    )

    # The unique reference ID generated by Paystack for this transaction.
    paystack_ref: Mapped[str] = mapped_column(
        String(100),
        unique=True,
        nullable=False,
        index=True
    )

    # The locked price ID or details from the 'pricing' table/cache at the
    # time of transaction initiation. This is a critical field for integrity.
    # For now, we'll store a reference string.
    locked_price_ref: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Reference to the price that was locked for this transaction."
    )

    # --- Relationships ---
    # This creates the other side of the User-Payment relationship.
    user: Mapped["User"] = relationship(
        "User",
        back_populates="payments"
    )

    def __repr__(self) -> str:
        return (
            f"<Payment(id={self.id}, user_id={self.user_id}, "
            f"amount_ngn={self.amount_ngn}, status='{self.status}')>"
        )