from __future__ import annotations
from typing import TYPE_CHECKING

from sqlalchemy import String, ForeignKey, Integer
from sqlalchemy.orm import Mapped, mapped_column, relationship

from models.base import BaseModel
from config.constants import DEFAULT_CURRENCY

if TYPE_CHECKING:
    from .user import User
    from .number import Number

class Payment(BaseModel):
    """
    Represents a payment transaction.
    """
    __tablename__ = "payments"

    # Foreign key linking this payment to a user.
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # The amount in NGN (in the smallest currency unit, e.g., kobo).
    amount_ngn: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Amount in the smallest currency unit (e.g., kobo for NGN)"
    )

    # The currency of the transaction.
    currency: Mapped[str] = mapped_column(
        String(3),
        default=DEFAULT_CURRENCY,
        nullable=False
    )

    # The status of the payment.
    status: Mapped[str] = mapped_column(
        String(50),
        default="pending",
        nullable=False,
        index=True
    )

    # The unique reference ID generated by Paystack.
    paystack_ref: Mapped[str] = mapped_column(
        String(100),
        unique=True,
        nullable=False,
        index=True
    )

    # The locked price reference from the pricing cache.
    locked_price_ref: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Reference to the price that was locked for this transaction."
    )
    
    # --- Relationships ---
    user: Mapped["User"] = relationship("User", back_populates="payments")
    
    # The number that was purchased with this payment (if any)
    number: Mapped["Number"] = relationship("Number", back_populates="payment", uselist=False)

    def __repr__(self) -> str:
        return (
            f"<Payment(id={self.id}, user_id={self.user_id}, "
            f"amount_ngn={self.amount_ngn}, status='{self.status}')>"
        )
